["Applications/eikana.app"]
    type = "archive"
    url = "https://github.com/iMasanari/cmd-eikana/releases/download/v2.2.3/eikana-2.2.3.app.zip"
    exact = true
    stripComponents = 0
    refreshPeriod = "168h"
