format = """\
[](bg:#131921FF fg:#1C3A5E)\
$directory\
[ ](fg:#1C3A5E bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[ ](fg:#FCF392 bg:#3B76F0)\
$hostname\
[ ](fg:#3B76F0 bg:#131921FF)\
$fill\
[](bg:#131921FF fg:#1C3A5E)\
$time\
[](bg:#131921FF fg:#1C3A5E)\
\n$character\
"""

add_newline = false

[fill]
symbol = ' '

[directory]
format = "[  $path ]($style)"
style = "fg:#8DFBD2 bg:#1C3A5E"

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[$symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[󰅐 $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[󱑍 $time](bg:#1C3A5E fg:#8DFBD2)]($style)'

[line_break]
disabled = true

[hostname]
ssh_only = true
ssh_symbol = "🌐 "
format = '[$hostname]($style)'
style = "fg:#2D1C63 bg:#9A86FD"
disabled = false
